[project]
name = "midas"
version = "0.1.0"
description = "A static-first type checking framework for Python data-frames"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Louis Heredero", email = "louis.heredero@students.hevs.ch" },
]
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "black>=26.5.1",
    "click>=8.4.1",
    "watchdog>=6.0.0",
]

[project.urls]
Homepage = "https://git.kbk28.ch/HEL/midas"
Repository = "https://git.kbk28.ch/HEL/midas"

[project.scripts]
midas = "midas.cli.main:midas"

[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'
