name: Compile manual
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Setup Fontist
        uses: fontist/setup-fontist@v2

      - name: Install Fonts
        run: fontist manifest install docs/fonts.yaml

      - uses: typst-community/setup-typst@v5
        with:
          typst-version: "0.15.0"
          zip-packages: docs/requirements.json
          cache-local-packages: true
          token: ""

      - run: |
          typst compile \
            --root . \
            --font-path ~/.fontist/fonts \
            docs/manual.typ \
            docs/manual.pdf

      - name: Upload artifact
        uses: christopherhx/gitea-upload-artifact@v4
        with:
          name: manual
          path: docs/manual.pdf
