name: Tests
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - "**"

jobs:
  tests:
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml
      - run: python3 -m tests
