Identifier ::= '[a-zA-Z][a-zA-Z_]*'

TypeArgs ::= "[" (Type ("," Type)*)? "]"

FrameColumn ::= ((Identifier | "_") ":")? Type
FrameSchema ::= "[" (FrameColumn ("," FrameColumn)*)? "]"

Type ::= "Frame" FrameSchema | Identifier TypeArgs?
