from __future__ import annotations
from typing import Generic, TypeVar

class Currency(float): ...

_T0 = TypeVar("_T0", bound=Currency, covariant=True)

class Price(Currency, Generic[_T0]):
    def __add__(self, _0: Price[_T0], /) -> Price[_T0]: ...

class EUR(Currency): ...
class USD(Currency): ...
class CHF(Currency): ...
class Discount(float): ...
