"""
This file was generated by a script. Any manual changes might be overwritten.
Please modify gen/python.py instead and run gen/gen.py
"""

from __future__ import annotations

import ast
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Generic, Optional, TypeVar

from midas.ast.location import Location

T = TypeVar("T")

####################
# Type annotations #
####################


@dataclass(frozen=True, kw_only=True)
class MidasType(ABC):
    location: Optional[Location] = None

    @abstractmethod
    def accept(self, visitor: Visitor[T]) -> T: ...

    class Visitor(ABC, Generic[T]):
        @abstractmethod
        def visit_base_type(self, node: BaseType) -> T: ...

        @abstractmethod
        def visit_constraint_type(self, node: ConstraintType) -> T: ...

        @abstractmethod
        def visit_frame_column(self, node: FrameColumn) -> T: ...

        @abstractmethod
        def visit_frame_type(self, node: FrameType) -> T: ...


@dataclass(frozen=True)
class BaseType(MidasType):
    base: str
    param: Optional[MidasType]

    def accept(self, visitor: MidasType.Visitor[T]) -> T:
        return visitor.visit_base_type(self)


@dataclass(frozen=True)
class ConstraintType(MidasType):
    type: MidasType
    constraint: ast.expr

    def accept(self, visitor: MidasType.Visitor[T]) -> T:
        return visitor.visit_constraint_type(self)


@dataclass(frozen=True)
class FrameColumn(MidasType):
    name: Optional[str]
    type: Optional[MidasType]

    def accept(self, visitor: MidasType.Visitor[T]) -> T:
        return visitor.visit_frame_column(self)


@dataclass(frozen=True)
class FrameType(MidasType):
    columns: list[FrameColumn]

    def accept(self, visitor: MidasType.Visitor[T]) -> T:
        return visitor.visit_frame_type(self)


##############
# Statements #
##############


@dataclass(frozen=True, kw_only=True)
class Stmt(ABC):
    location: Optional[Location] = None

    @abstractmethod
    def accept(self, visitor: Visitor[T]) -> T: ...

    class Visitor(ABC, Generic[T]):
        @abstractmethod
        def visit_function(self, stmt: Function) -> T: ...


@dataclass(frozen=True)
class Function(Stmt):
    name: str
    posonlyargs: list[Argument]
    args: list[Argument]
    kwonlyargs: list[Argument]
    returns: Optional[MidasType]

    @dataclass(frozen=True, kw_only=True)
    class Argument:
        location: Optional[Location] = None
        name: Optional[str]
        type: Optional[MidasType]

    def accept(self, visitor: Stmt.Visitor[T]) -> T:
        return visitor.visit_function(self)
